engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- test/**/*
- docs/**/*
- demo/**/*
